### ISSUE TITLE
Style updates: search form

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#163]
## testing notes
**designs**
[desktop](https://zpl.io/bLxAOGB) / [tablet](https://zpl.io/agr04BA) / [mobile](https://zpl.io/brlZNq7)

just the form part. this includes the new "start hidden" advanced search toggle behavior, and the new collection button behavior/styles.

**Comment by mnaydan** [comment]
The advanced search collapse works elegantly across devices. As discussed on Slack, the collections buttons are not stacked correctly (unselected collections should appear on a second line). The x's in chrome are black instead of white (FF is fine), and on iPad and iPhone (Safari) they are just large black squares. On Chrome empty collections (literary, linguistics) don't display the x at all (in FF it does). On all browsers the x gets a halo around it, changes to an arrow instead of a mickey mouse hand on hover, and disappears when clicked.
<img width="957" alt="screen shot 2018-12-11 at 5 37 20 pm" src="https://user-images.githubusercontent.com/22945600/49834858-73be9d00-fd6b-11e8-9d8d-10414fe876da.png">

**Comment by thatbudakguy** [comment]
- x's shouldn't be selectable or have boxes around them now (just "mickey mouse hand")
- buttons should stack correctly now (disabled buttons are sorted on the same line as, but after, non-active buttons)

**Comment by mnaydan** [comment]
On Chrome only (Safari and FF are fine) a shadow-halo remains around the button after you click on it until you click elsewhere. We need to remove this. 

x color and interaction behavior is fixed, and buttons stack correctly.

**Comment by thatbudakguy** [comment]
@mnaydan based on some [comments here](https://stackoverflow.com/questions/19053181/how-to-remove-focus-around-buttons-on-click) and [this article](https://hackernoon.com/removing-that-ugly-focus-ring-and-keeping-it-too-6c8727fefcd2) it seems like chrome on OSX in particular is showing that focus style when buttons are clicked. the problem is, I can't hide that style because it's the only way that keyboard users know when they're focused on a button (try hitting tab a bunch of times and navigating around the form - the shadow shows where you are). the linked article goes to great lengths to try to fix this (basically by trying to "detect" if someone is a keyboard user) and I don't think we should try to do that, so for now I think we need to live with the extra shadow in Chrome.

weird iPad and iPhone are indeed weird...I'll see if I can find an iOS device to replicate this for testing.

**Comment by mnaydan** [comment]
@thatbudakguy thanks for the detective work! I had no idea it was that complicated. We can live with it. 

Lmk if you can replicate and if you think iPad/iPhone are worth fixing now or we should kick it down the road.

**Comment by thatbudakguy** [comment]
a couple of things went into fixing this for iOS devices; documenting here mostly for my sanity.

1. iOS safari doesn't respect `-webkit-appearance:none;`. solution:
```css
        input[type=checkbox] {
            position: absolute;
            z-index: -1;
        }
```
(this is in addition to the vendor-prefixed `appearance:none;` stuff, plus the hiding the `::ms-check` pseudo-element for Edge).

2. Adding `::before` or `::after` pseudo-elements to an `<input>` isn't technically supported. solution: make sure the input is wrapped in a label and add the pseudo-element to the label instead.
```html
<label class="button active" role="checkbox">
    <input type="checkbox" checked="">
    checkbox name
</label>          
```
```css
        .button::after { // add the white "x"
            content: "×";
            cursor: pointer;
            color: white;
            position: absolute;
            font-size: 1rem;
            right: 5px;
            top: 5px;
            opacity: 0;
            transition: opacity 0.2s;
        }

        .button.active::after { // fade it in
            opacity: 1;
        }

        .button.active { // create extra space when the "x" is visible
            padding-right: 1.25rem;
        }
```
