### ISSUE TITLE
As a user, I want my results updated as soon as I change my search options so that I can refine my search without losing my place in the form and have results load more quickly.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#65]
## testing notes
- no need to hit <kbd>enter</kbd>!
- the histogram should update when your results change.
- the result count should update when your results change.
- pagination controls should update when your results change.
- clicking "clear selection" on the dates should update the results.
- changing the sort or the collection filters should update the results.
- if you don't have anything entered in keyword, title, or author, you shouldn't be able to sort by relevance (that wouldn't make any sense!)
- if you have relevance selected as a sort and you delete all your queries, you should get switched to title (a-z) sort instead.

**Comment by jabauer** [comment]
On iOS "done" button does not submit the form, have to hit "return" on virtual keypad. On Android "enter" moves to the next form field but does not submit.

**Comment by xinyil** [comment]
submitting when clicking out the form would be good!

**Comment by thatbudakguy** [comment]
ok, so as per #63 I know I need to make the publication date inputs submit when you unfocus them. We probably shouldn't do that for the text inputs though because it would mean you couldn't do e.g. an author and title query at the same time (which works great currently).

If I understand you @xinyil we could make clicking in a place that isn't the form (anywhere else on the page) submit the form, which I think would work but maybe isn't what the user would expect for mobile? I'm curious why mobile currently doesn't show a "submit" button in the native interface - only ways to move back and forth between fields (@rlskoeser and I confirmed this on android too). The form will submit if you get to the last field and hit "next", but only then.

Currently there's actually a hidden submit button, which is why pressing "enter" on the text fields works...just don't know why mobile isn't picking it up.

**Comment by xinyil** [comment]
hitting "done" each form on iOS should submit the form. 

related discussions:
https://stackoverflow.com/questions/5665203/getting-iphone-go-button-to-submit-form?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
> On a whim, we changed display: none to margin-left: -1000px
> Apparently, Safari is looking for the presence of a SUBMIT button in the form and only if it's not display: none, it will then fire it when you hit the GO button.

**Comment by thatbudakguy** [comment]
@xinyil whoa this is super interesting, thanks for sharing. I'll try using the margin hack to make the button offscreen but still "visible".

**Comment by thatbudakguy** [comment]
I'll update the testing notes as we nail down how we want this to work.

**Comment by thatbudakguy** [comment]
so, I'm actually not using `display:none;` anymore - instead it's using the accessibility utility classes I used on derrida.
```scss
.sr-only { // hide for all but screen readers
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    white-space: nowrap;
    border: 0;
}

.sr-only-focusable { // ensure only screen readers can focus
    &:active,
    &:focus {
      position: static;
      width: auto;
      height: auto;
      overflow: visible;
      clip: auto;
      white-space: normal;
  }
}
```
seems like this should be avoiding the safari problem...not sure why it doesn't work
