### ISSUE TITLE
Footer is "flashing" on page due to movement via javascript

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/ppa-django#86]
## testing notes
- footer shouldn't "flash" or move around on the page; it should appear at the bottom automatically.
- footer should stay the correct distance from main page content, even when page is resized (try on the main archive search page; make sure it's all the way at the bottom and trying resizing your window to be skinnier)
- on pages that are shorter than screen height (e.g. "what is prosody"), footer should "stick" to the bottom.

## dev notes
this is an unsolved problem from #48.

ideally we can use one of the last to solutions [here](https://css-tricks.com/couple-takes-sticky-footer/) to solve the problem without using javascript.

**Comment by thatbudakguy** [comment]
OK, managed to implement this using scss. For future reference, our semantic UI DOM looks roughly like:
```html
<html>
  <body class="pushable">
    <mobile nav menu />
    <main nav menu />
    <div class="pusher"> <!-- this moves the content when you open the hamburger menu -->
      <header />
      <main />
      <footer />
    </div>
  </body>
</html>
```
The relevant scss was basically:
```scss
.pushable > .pusher {
    display: flex;
    flex-direction: column;
    height: 100%;
    overflow-y: auto;
}
main {
    flex: 1 0 auto;
}
footer {
    margin-bottom: 0;
    width: 100%;
}
```
